// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkppRwJcoUsNr8aZOPj4Ob9a446SObwaE',
    appId: '1:739304125787:web:8bd882238ed7ea5c0fd67e',
    messagingSenderId: '739304125787',
    projectId: 'gr06-zerowaste-25-inters-b6030',
    authDomain: 'gr06-zerowaste-25-inters-b6030.firebaseapp.com',
    storageBucket: 'gr06-zerowaste-25-inters-b6030.firebasestorage.app',
    measurementId: 'G-HKVDRC8TYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg12UsX3C16C5EtO8U3ptZvL9l9YPvAAE',
    appId: '1:739304125787:android:daad3462e9d649bc0fd67e',
    messagingSenderId: '739304125787',
    projectId: 'gr06-zerowaste-25-inters-b6030',
    storageBucket: 'gr06-zerowaste-25-inters-b6030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLBt13lxGv2b5QsM9KHvxofL-JMer9UA',
    appId: '1:739304125787:ios:c5aefef6c3ada8470fd67e',
    messagingSenderId: '739304125787',
    projectId: 'gr06-zerowaste-25-inters-b6030',
    storageBucket: 'gr06-zerowaste-25-inters-b6030.firebasestorage.app',
    iosBundleId: 'com.example.zerowasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOLBt13lxGv2b5QsM9KHvxofL-JMer9UA',
    appId: '1:739304125787:ios:c5aefef6c3ada8470fd67e',
    messagingSenderId: '739304125787',
    projectId: 'gr06-zerowaste-25-inters-b6030',
    storageBucket: 'gr06-zerowaste-25-inters-b6030.firebasestorage.app',
    iosBundleId: 'com.example.zerowasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkppRwJcoUsNr8aZOPj4Ob9a446SObwaE',
    appId: '1:739304125787:web:d65be489b16689760fd67e',
    messagingSenderId: '739304125787',
    projectId: 'gr06-zerowaste-25-inters-b6030',
    authDomain: 'gr06-zerowaste-25-inters-b6030.firebaseapp.com',
    storageBucket: 'gr06-zerowaste-25-inters-b6030.firebasestorage.app',
    measurementId: 'G-ZPBPEYKZ44',
  );
}
