// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrzHqycwjfLrP4PHpd1mUtKHT3m0bilk',
    appId: '1:1031956156307:web:59e782fea9047a29a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    authDomain: 'gr06-zerowaste-25-intersession.firebaseapp.com',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
    measurementId: 'G-FFCG11VB0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCflJVbCnPiNs1_KhJrRRfWXIpOuahelU',
    appId: '1:1031956156307:android:c00afd4bc519dba5a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUsm__NIwwDNxIlChRP2yptBRFcb-qLOQ',
    appId: '1:1031956156307:ios:62b49be9ddbac518a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
    iosBundleId: 'com.example.zerowasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUsm__NIwwDNxIlChRP2yptBRFcb-qLOQ',
    appId: '1:1031956156307:ios:62b49be9ddbac518a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
    iosBundleId: 'com.example.zerowasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbrzHqycwjfLrP4PHpd1mUtKHT3m0bilk',
    appId: '1:1031956156307:web:f2215f5654c9bd3ea3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    authDomain: 'gr06-zerowaste-25-intersession.firebaseapp.com',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
    measurementId: 'G-V6ZYJ17DYJ',
  );
}
