// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17WelCjZ33qX_DSz8RitdKZ1gaq_LC9A',
    appId: '1:1031956156307:web:59e782fea9047a29a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    authDomain: 'gr06-zerowaste-25-intersession.firebaseapp.com',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
    measurementId: 'G-FFCG11VB0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6Sg--2_TK2y22950yy6rHMxXlsyOGC4',
    appId: '1:1031956156307:android:c00afd4bc519dba5a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjy47b8n93tUmzeqGGLsiX6fJdPzM0R4',
    appId: '1:1031956156307:ios:62b49be9ddbac518a3a266',
    messagingSenderId: '1031956156307',
    projectId: 'gr06-zerowaste-25-intersession',
    storageBucket: 'gr06-zerowaste-25-intersession.firebasestorage.app',
    androidClientId: '1031956156307-q73s62vkqfmp4nbdal6bt3663hplr0dt.apps.googleusercontent.com',
    iosClientId: '1031956156307-lp65fe05rouq61ho3jed7uqtpahrko7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.zerowasteApp',
  );
}
